# Generated by Django 5.1.5 on 2026-07-29 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('visitor_name', models.CharField(blank=True, max_length=140)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, max_length=40)),
                ('is_qualified_lead', models.BooleanField(db_index=True, default=False)),
                ('summary', models.TextField(blank=True)),
                ('referrer_path', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Visitor'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
                ('referenced_products', models.ManyToManyField(blank=True, to='catalog.product')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
