# Generated by Django 5.1.5 on 2026-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=140)),
                ('issuer', models.CharField(blank=True, max_length=140)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('badge', models.ImageField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=140)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('question', models.CharField(max_length=280)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('page', models.CharField(db_index=True, default='home', help_text='Which page this FAQ belongs to (home, products, contact…).', max_length=40)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='library/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('tags', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('year', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['order', 'year'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('duration', models.CharField(blank=True, help_text='e.g. Within 24 hrs', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('summary', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='["Point one", "Point two"]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('label', models.CharField(max_length=80)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, help_text='e.g. + or %', max_length=10)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=140)),
                ('role', models.CharField(max_length=140)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=140)),
                ('company', models.CharField(blank=True, max_length=140)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('source', models.CharField(choices=[('google', 'Google Review'), ('direct', 'Direct'), ('linkedin', 'LinkedIn')], default='direct', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=280)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Why-NOKS card',
                'verbose_name_plural': 'Why-NOKS cards',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
