# Generated by Django 5.1.5 on 2026-08-10 13:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='documents/%Y/%m/'),
        ),
    ]
