# Generated by Django 5.1.5 on 2026-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_generated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
